// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAToXoVWE5vuOfJIlKu0lkfpE-UcQD2-dE',
    appId: '1:119322401983:web:d51adf64b3fcf50e5aba0a',
    messagingSenderId: '119322401983',
    projectId: 'cmsc23-todo-app-jbisanan',
    authDomain: 'cmsc23-todo-app-jbisanan.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jbisanan.appspot.com',
    measurementId: 'G-F2439KY4VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgMUAjtQtpH5bI45rolfhrxlhsMUjU7U',
    appId: '1:119322401983:android:d1f7eccaebf7b61b5aba0a',
    messagingSenderId: '119322401983',
    projectId: 'cmsc23-todo-app-jbisanan',
    storageBucket: 'cmsc23-todo-app-jbisanan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK8QKMaJieCQmu6HUPJIBYC2qKhLYOd9Y',
    appId: '1:119322401983:ios:dde9f409e75a1e465aba0a',
    messagingSenderId: '119322401983',
    projectId: 'cmsc23-todo-app-jbisanan',
    storageBucket: 'cmsc23-todo-app-jbisanan.appspot.com',
    iosClientId:
        '119322401983-vms8q1q6ld8pomobv1bev14ci2ugrdnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK8QKMaJieCQmu6HUPJIBYC2qKhLYOd9Y',
    appId: '1:119322401983:ios:dde9f409e75a1e465aba0a',
    messagingSenderId: '119322401983',
    projectId: 'cmsc23-todo-app-jbisanan',
    storageBucket: 'cmsc23-todo-app-jbisanan.appspot.com',
    iosClientId:
        '119322401983-vms8q1q6ld8pomobv1bev14ci2ugrdnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
